// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIForteT.Data;

namespace WebAPIForteT.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210913225749_addMigrationPermisos")]
    partial class addMigrationPermisos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPIForteT.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidosEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPermiso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPermisoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoPermisoId");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidosEmpleado = "Sosa Juarez",
                            FechaPermiso = new DateTime(2021, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "Roberto",
                            TipoPermisoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApellidosEmpleado = "Pinales Lopez",
                            FechaPermiso = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "Nataly",
                            TipoPermisoId = 1
                        },
                        new
                        {
                            Id = 3,
                            ApellidosEmpleado = "Sandoval Jaramillo",
                            FechaPermiso = new DateTime(2021, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "Mateo",
                            TipoPermisoId = 4
                        },
                        new
                        {
                            Id = 4,
                            ApellidosEmpleado = "Rodriguez Gracia",
                            FechaPermiso = new DateTime(2021, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "Karla",
                            TipoPermisoId = 3
                        });
                });

            modelBuilder.Entity("WebAPIForteT.Models.TipoPermiso", b =>
                {
                    b.Property<int>("TipoPermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoPermisoId");

                    b.ToTable("TipoPermisos");

                    b.HasData(
                        new
                        {
                            TipoPermisoId = 1,
                            Descripcion = "Enfermedad"
                        },
                        new
                        {
                            TipoPermisoId = 2,
                            Descripcion = "Diligencias"
                        },
                        new
                        {
                            TipoPermisoId = 3,
                            Descripcion = "Matrimonio"
                        },
                        new
                        {
                            TipoPermisoId = 4,
                            Descripcion = "Mudanza"
                        });
                });

            modelBuilder.Entity("WebAPIForteT.Models.Permiso", b =>
                {
                    b.HasOne("WebAPIForteT.Models.TipoPermiso", "TipoPermiso")
                        .WithMany("Permisos")
                        .HasForeignKey("TipoPermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPermiso");
                });

            modelBuilder.Entity("WebAPIForteT.Models.TipoPermiso", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
